/* Generated by qat/scripts/gen_h7_branched.py -- do not edit. */
#ifndef RA_MODEL_H
#define RA_MODEL_H

#include "ra_kernel.h"

#define RA_MODEL_NAME    "solid_v2"
#define RA_OBS_FEATURES  25
#define RA_HIST_FEATURES 125
#define RA_LATENT_DIM    3
#define RA_ACT_FEATURES  6
#define RA_JOIN_FEATURES 28
#define RA_SCRATCH       128
#define RA_WEIGHT_BYTES  78418
#define RA_MACS          38400
#define RA_ENC_LAYERS    3
#define RA_ACT_LAYERS    4
#define RA_LAYERS        7

extern const ra_model_t ra_model_enc;
extern const ra_model_t ra_model_act;

/* obs_q[RA_OBS_FEATURES], hist_q[RA_HIST_FEATURES] -> act_q[RA_ACT_FEATURES].
 * Caller owns the buffers; nothing is allocated here. Sizes:
 *   join[RA_JOIN_FEATURES], scratch[2 * RA_SCRATCH]
 * (the kernel ping-pongs between scratch and scratch + RA_SCRATCH). */
static inline void ra_infer_wheelleg(
        const int16_t *obs_q, const int16_t *hist_q, int16_t *act_q,
        int16_t *join, int16_t *scratch)
{
    int16_t latent[RA_LATENT_DIM];
    ra_infer_simd(&ra_model_enc, hist_q, latent, scratch);
    for (uint16_t i = 0; i < RA_OBS_FEATURES; ++i)
        join[i] = obs_q[i];
    for (uint16_t i = 0; i < RA_LATENT_DIM; ++i)
        join[RA_OBS_FEATURES + i] = latent[i];
    ra_infer_simd(&ra_model_act, join, act_q, scratch);
}

#endif