#!/usr/bin/env python3
"""Emit an H7 model for the branched wheel-legged policy. goal.md section 17.

`ra_kernel.c` walks a flat `ra_layer_t` list, so it can only express a single
feed-forward chain. This policy is not one: the encoder consumes the history,
its 3-d latent is concatenated with the 25-d observation, and the actor
consumes the join. That is why the existing `tools/gen_h7_model.py` cannot
build it -- `FixedPointPolicy` collapses every Gemm into one chain and would
silently wire the wrong graph.

Rather than change the kernel, the graph is decomposed into the two chains it
already supports, with the concat done as a splice between them:

    ra_model_enc : 125 -> 128 -ELU-> 64 -ELU-> 3     (latent, Q8.8)
    splice       : buf[0:25] = obs_q ; buf[25:28] = latent_q
    ra_model_act : 28 -> 128 -ELU-> 64 -ELU-> 32 -ELU-> 6

The splice is a copy of int16 on a shared grid, which is exactly what the PL
CONCAT descriptor does (shift = 0). No new arithmetic is introduced, so the
result stays bit-identical to the FPGA and to `roboaccel_quant/fixed_ref.py`; the emitted
golden vectors are what proves it on the board.
"""
from __future__ import annotations

import argparse, sys
from pathlib import Path

import numpy as np

QUANT_ROOT = Path(__file__).resolve().parent.parent   # quantization/
sys.path.insert(0, str(QUANT_ROOT))

from roboaccel_quant.quant_policy import build_from_onnx  # noqa: E402
from roboaccel_quant.torch_hw import QuantConfig  # noqa: E402

PAD = 4     # rows padded to a multiple of 4 int16 so SMLALD needs no tail


def carr(name: str, values, per_line: int = 16) -> list[str]:
    flat = np.asarray(values).reshape(-1).astype(np.int64)
    out = [f"const int16_t {name}[{flat.size}] __attribute__((aligned(8))) = {{"]
    for i in range(0, flat.size, per_line):
        out.append("    " + ", ".join(str(int(v)) for v in flat[i:i + per_line]) + ",")
    out.append("};")
    return out


def emit_chain(src: list[str], tag: str, layers) -> tuple[int, int, int]:
    wbytes = 0
    for i, L in enumerate(layers):
        k, n = int(L.wq.shape[1]), int(L.wq.shape[0])
        stride = ((k + PAD - 1) // PAD) * PAD
        padded = np.zeros((n, stride), dtype=np.int64)
        padded[:, :k] = L.wq
        src += carr(f"ra_{tag}_w{i}", padded)
        src += carr(f"ra_{tag}_b{i}", L.bq)
        src.append("")
        wbytes += padded.size * 2 + L.bq.size * 2
    src.append(f"static const ra_layer_t ra_{tag}_layers[] = {{")
    for i, L in enumerate(layers):
        k, n = int(L.wq.shape[1]), int(L.wq.shape[0])
        stride = ((k + PAD - 1) // PAD) * PAD
        src.append(f"    {{ ra_{tag}_w{i}, ra_{tag}_b{i}, {k}, {n}, {stride}, "
                   f"{L.f_w}, {1 if L.elu else 0} }},")
    src.append("};")
    kin = int(layers[0].wq.shape[1])
    nout = int(layers[-1].wq.shape[0])
    scratch = max(max(int(L.wq.shape[0]), int(L.wq.shape[1])) for L in layers)
    scratch = ((scratch + PAD - 1) // PAD) * PAD
    src += ["", f"const ra_model_t ra_model_{tag} = {{",
            f"    ra_{tag}_layers, {len(layers)}, {kin}, {nout}, {scratch}", "};", ""]
    return wbytes, scratch, sum(int(L.wq.size) for L in layers)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("onnx", type=Path)
    ap.add_argument("--name", required=True)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--golden", type=int, default=8)
    ap.add_argument("--golden-npz", type=Path,
                    help="use the regime-spanning golden set instead of random "
                         "inputs (goal.md section 11)")
    args = ap.parse_args()

    net = build_from_onnx(args.onnx, QuantConfig())
    ref = net.to_fixed_ref()
    n_obs, n_hist = net.num_obs, int(ref.enc[0].wq.shape[1])
    n_lat = int(ref.enc[-1].wq.shape[0])
    n_act = int(ref.act[-1].wq.shape[0])

    src = ['#include "ra_kernel.h"', ""]
    wb_e, sc_e, mac_e = emit_chain(src, "enc", ref.enc)
    wb_a, sc_a, mac_a = emit_chain(src, "act", ref.act)

    hdr = ["/* Generated by qat/scripts/gen_h7_branched.py -- do not edit. */",
           "#ifndef RA_MODEL_H", "#define RA_MODEL_H", "",
           '#include "ra_kernel.h"', "",
           f'#define RA_MODEL_NAME    "{args.name}"',
           f"#define RA_OBS_FEATURES  {n_obs}",
           f"#define RA_HIST_FEATURES {n_hist}",
           f"#define RA_LATENT_DIM    {n_lat}",
           f"#define RA_ACT_FEATURES  {n_act}",
           f"#define RA_JOIN_FEATURES {n_obs + n_lat}",
           f"#define RA_SCRATCH       {max(sc_e, sc_a, n_obs + n_lat)}",
           f"#define RA_WEIGHT_BYTES  {wb_e + wb_a}",
           f"#define RA_MACS          {mac_e + mac_a}",
           f"#define RA_ENC_LAYERS    {len(ref.enc)}",
           f"#define RA_ACT_LAYERS    {len(ref.act)}",
           f"#define RA_LAYERS        {len(ref.enc) + len(ref.act)}",
           "",
           "extern const ra_model_t ra_model_enc;",
           "extern const ra_model_t ra_model_act;", "",
           "/* obs_q[RA_OBS_FEATURES], hist_q[RA_HIST_FEATURES] -> act_q[RA_ACT_FEATURES].",
           " * Caller owns the buffers; nothing is allocated here. Sizes:",
           " *   join[RA_JOIN_FEATURES], scratch[2 * RA_SCRATCH]",
           " * (the kernel ping-pongs between scratch and scratch + RA_SCRATCH). */",
           "static inline void ra_infer_wheelleg(",
           "        const int16_t *obs_q, const int16_t *hist_q, int16_t *act_q,",
           "        int16_t *join, int16_t *scratch)",
           "{",
           "    int16_t latent[RA_LATENT_DIM];",
           "    ra_infer_simd(&ra_model_enc, hist_q, latent, scratch);",
           "    for (uint16_t i = 0; i < RA_OBS_FEATURES; ++i)",
           "        join[i] = obs_q[i];",
           "    for (uint16_t i = 0; i < RA_LATENT_DIM; ++i)",
           "        join[RA_OBS_FEATURES + i] = latent[i];",
           "    ra_infer_simd(&ra_model_act, join, act_q, scratch);",
           "}", "", "#endif"]

    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "ra_model.c").write_text("\n".join(src), encoding="ascii")
    (args.out / "ra_model.h").write_text("\n".join(hdr), encoding="ascii")

    # Golden vectors, computed by the reference the FPGA also agrees with.
    if args.golden_npz:
        d = np.load(args.golden_npz)
        obs = d["obs"].astype(np.float32).astype(np.float64)
        hist = d["obs_history"].astype(np.float32).astype(np.float64)
        if args.golden and args.golden < len(obs):
            # Even stride keeps every regime represented; the npz is grouped.
            sel = np.linspace(0, len(obs) - 1, args.golden).astype(int)
            obs, hist = obs[sel], hist[sel]
        args.golden = len(obs)
        print(f"  golden set: {args.golden} vectors from {args.golden_npz.name}")
    else:
        rng = np.random.default_rng(17)
        obs = rng.normal(0, 0.4, (args.golden, n_obs)).astype(np.float32).astype(np.float64)
        hist = rng.normal(0, 0.4, (args.golden, n_hist)).astype(np.float32).astype(np.float64)
    oq, hq, aq = [], [], []
    for i in range(args.golden):
        o = ref.quantize_obs(obs[i]); h = ref.quantize_obs(hist[i])
        a, _ = ref.run_int(o, h)
        oq.append(o); hq.append(h); aq.append(a)
    gold = ["/* Generated by qat/scripts/gen_h7_branched.py -- do not edit. */",
            "#ifndef RA_GOLDEN_H", "#define RA_GOLDEN_H", "",
            "#include <stdint.h>", "", f"#define RA_GOLDEN_COUNT {args.golden}", ""]
    gold += carr("ra_golden_obs", np.array(oq))
    gold += carr("ra_golden_hist", np.array(hq))
    gold += carr("ra_golden_act", np.array(aq))
    gold += ["", "#endif"]
    (args.out / "ra_golden.h").write_text("\n".join(gold), encoding="ascii")

    print(f"{args.name}: obs {n_obs} hist {n_hist} latent {n_lat} act {n_act}")
    print(f"  encoder {len(ref.enc)} layers, {mac_e:,} MAC, {wb_e:,} B")
    print(f"  actor   {len(ref.act)} layers, {mac_a:,} MAC, {wb_a:,} B")
    print(f"  total {mac_e + mac_a:,} MAC, {wb_e + wb_a:,} B padded weights, "
          f"scratch {max(sc_e, sc_a, n_obs + n_lat)}")
    print(f"  wrote {args.out}/ra_model.c, ra_model.h, ra_golden.h")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
